API_ID: 26170756
API_HASH: 4f4f0d8f3db6210ab6a7bfc8f1ee9f15
BOT_TOKEN: 6102944243:AAHl99uKWiMgFVdvH4mFdCzbaM5iSL4vi3Y


MONGO_URL: mongodb+srv://fwalidfree:UsRlxfo36jdGhBmt@cluster0.h3ut5jd.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-12952.c8.us-east-1-3.ec2.cloud.redislabs.com
REDIS_PORT: 12952
REDIS_PASS: gWaBOk1L2ygl9XunBvQovVW2gk4BXjZ7

SESSION_API_ID: 26170756
SESSION_API_HASH: 4f4f0d8f3db6210ab6a7bfc8f1ee9f15
SESSION_STRING: 1BJWap1sBu2cpnwjdQyVgQTWWp_gEY_VpA6J0lAgnvKZf7vXhnThxZFf9076Ri4v9jz2hSCDC15iwqJsU38Jhhx1orx_zU22wcfd-g3Yn1D75yM7QfAA5GPBXuTbYAI-U-HVAxqY7trhi-z2GhzMj7cSnJzia_6RZx1EHNTfGoJMXnJYlJtBgMhuRqVTk930K9OtF2pufLRP_o0C4PPJhhCP19sqacoFoZ-QggUuU0-W1M1RMuMwfCekVbzIvVDNMTvqgU7vovZZPA0hTMgpgKoWJw-pWG2HeZQMspeAbunSj74ccB6sqCmX0cy1YHJBPJ0HgxVF8tPwlp8ujxRfVuAMHpnmGNMI=

ADMINS: 
  - 6128902625

OWNER: 6128902625

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: FWMain 
LOG_CHAT: FWMainChat

HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"