API_ID: 24985686
API_HASH: fc3946cec9755c3f1907fe32ec3d8413
BOT_TOKEN: 6069949824:AAFfPuCausJ7jJsg8i1Flml2Uubehr49e2s


MONGO_URL: mongodb+srv://fwalidfree:UsRlxfo36jdGhBmt@cluster0.h3ut5jd.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-12952.c8.us-east-1-3.ec2.cloud.redislabs.com
REDIS_PORT: 12952
REDIS_PASS: gWaBOk1L2ygl9XunBvQovVW2gk4BXjZ7

SESSION_API_ID: 24985686
SESSION_API_HASH: fc3946cec9755c3f1907fe32ec3d8413
SESSION_STRING: 1BJWap1sBu3A97ll6naKuZ7RGOT1j7iG8gGLbhPxwCP6Yg2Xl173kt_UhBInwyp-vDBSLxGdUHx3p96105okz71EFOvxNNjtNrAybK6xUM6FigIUVnOMcnXNfcKYVArDRDaRc8o7bvgGhOA4EqqcyeMTZLrksPHcHfUlbTzfa42SlqJYNSNrVU21JQhnw-diGC90bJJnlr7z8tYqIJgRhcOF1BuYLVUN5hcT6un7Mi5eMiinitJxKlZKK5ThVx5l96Z1tBm3SMYdm4UdWe_DjjWOv7TtHT12yZzaLjxnYH69XFAPROV24_rZbs9gAPTJxvgL8iwElzkFpF-6wpfRsQWx6Kic3jD8=

ADMINS: 
  - 6226795504

OWNER: 6226795504

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: FWMainChat 
LOG_CHAT: -1001939566806



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

